# $NetBSD$
# used by tomtom/llvm7
# used by tomtom/clang7

LLVM_VERSION=   7.1.0
MASTER_SITES=   http://llvm.org/releases/${PKGVERSION_NOREV}/
#MASTER_SITES=   ${MASTER_SITE_GITHUB:=llvm/}
EXTRACT_SUFX=   .tar.xz
